#!/bin/bash

git add up
git add ./*.py
git add ./*.frag
git add ./*.vert
git add ./*.jpeg
git commit -m "$(date +%s)"
git remote add origin https://github.com/bobbysoon/Taxi3DPerpBisec.git
git remote -v
git push origin master $1

find . -name "*.pyc" -type f|xargs rm -f
